### PR TITLE
Awqmayo patch 3

### PR DESCRIPTION
**Pull request by awqmayo**
Fix issue with tradeoff questions not showing slider for more than one question

### CODE REVIEW

**Comment by awqmayo** [comment]
@brownsarahm @vrl2

**Comment by awqmayo** [comment]
@Elvictor01 @brownsarahm Sorry for the double tag; tagged someone other than Victor originally.

**Comment by Elvictor01** [comment]
I would check it out in a bit

**Review by Elvictor01 — APPROVED** [review]
The issue of tradeoff questions not showing slider for more than one question has been fixed @awqmayo @brownsarahm ...

But there seems to be an issue with the positioning of the x-axis values. I would create another issue for that. See the screenshot below
Alex Patch
.

**Pull request merged**
